name: continuum_workspace
publish_to: none

environment:
  sdk: ^3.10.4

workspace:
  - packages/continuum
  - packages/continuum_generator
  - packages/continuum_store_memory
  - packages/continuum_store_hive
  - packages/continuum_lints

dev_dependencies:
  melos: ^7.3.0

melos:
  ignore:
    - packages/**/example

  scripts:
    analyze:
      run: dart run melos exec --fail-fast -- "dart analyze ."
      description: Run static analysis in all packages.

    test:
      run: dart run melos exec --fail-fast -- "dart test"
      description: Run all package tests.
      packageFilters:
        dirExists: test
