name: continuum
description: An event sourcing library for Dart with code generation support.
version: 3.0.1
repository: https://github.com/zooper/continuum
homepage: https://zooper.dev

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  zooper_flutter_core: ^1.0.3

  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^6.0.0
  mockito: ^5.4.0
  test: ^1.25.6
