name: continuum_lints
description: Custom lint rules for continuum-based projects.
version: 4.0.0
repository: https://github.com/zooper/continuum
homepage: https://zooper.dev

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.0
  build: ^4.0.0
  custom_lint_builder: ^0.8.1
  path: ^1.9.0
  continuum: ^4.0.0

dev_dependencies:
  build_test: ^3.5.4
  lints: ^6.0.0
  test: ^1.25.6
