name: continuum_example
description: Example demonstrating the Continuum event sourcing library.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  continuum:
    path: ../

dev_dependencies:
  build_runner: ^2.4.15
  continuum_generator:
    path: ../../continuum_generator
