name: continuum_generator
description: Code generator for the continuum event sourcing library.
version: 1.0.0
repository: https://github.com/zooper/continuum
homepage: https://zooper.dev

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  analyzer: ^7.4.5
  build: ^2.4.0
  continuum: ^1.0.0
  source_gen: ^2.0.0
  glob: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.0
  build_test: ^2.2.0
  lints: ^6.0.0
  source_gen_test: ^1.0.0
  test: ^1.25.6
