name: continuum_lints_example
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  zooper_flutter_core: ^2.0.0
  bounded: ^1.0.0
  continuum:
    path: ../../continuum

dev_dependencies:
  custom_lint: ^0.8.1
  continuum_lints: ^4.0.0

dependency_overrides:
  continuum:
    path: ../../continuum
  continuum_lints:
    path: ..
